import type { ExerciseTemplate } from '@/src/types/exercise';

export const MEDITATION_TEMPLATES: ExerciseTemplate[] = [
  // MINDFULNESS BASICS
  {
    id: 'breath-awareness-5min',
    type: 'meditation',
    category: 'mindfulness_basics',
    name: 'Breath Awareness',
    description: 'A gentle 5-minute meditation focusing on your natural breath',
    duration: 5,
    icon: 'leaf-outline',
    color: '#059669',
    steps: [
      {
        id: 'intro',
        type: 'timed_speech',
        title: 'Finding Your Center',
        content: 'Getting settled',
        speechSegments: [
          { text: 'Find a comfortable position.', pauseAfter: 3 },
          { text: 'Gently close your eyes, or soften your gaze.', pauseAfter: 4 },
          { text: 'Take a deep breath in.', pauseAfter: 4, breathCue: true },
          { text: 'And slowly let it go.', pauseAfter: 4, breathCue: true },
          { text: 'Allow your breathing to return to its natural rhythm.', pauseAfter: 3 },
        ],
        voiceConfig: { rate: 0.8, pitch: 0.95 },
        required: true,
      },
      {
        id: 'main',
        type: 'timed_speech',
        title: 'Breath Awareness',
        content: 'Follow your breath',
        speechSegments: [
          { text: 'Now, bring your attention to your breath.', pauseAfter: 5 },
          { text: 'Notice the sensation of air entering your body.', pauseAfter: 8 },
          { text: 'Feel your chest and belly gently rise.', pauseAfter: 8 },
          { text: 'And then fall as you exhale.', pauseAfter: 8 },
          { text: 'There is nothing to change or fix.', pauseAfter: 5 },
          { text: 'Simply observe your breath as it is.', pauseAfter: 10 },
          { text: 'If your mind wanders, that is perfectly normal.', pauseAfter: 5 },
          { text: 'Gently guide your attention back to the breath.', pauseAfter: 10 },
          { text: 'Notice the pause between inhale and exhale.', pauseAfter: 8 },
          { text: 'And the pause between exhale and inhale.', pauseAfter: 10 },
          { text: 'Continue breathing naturally.', pauseAfter: 15 },
          { text: 'Each breath anchoring you to this moment.', pauseAfter: 15 },
        ],
        voiceConfig: { rate: 0.75, pitch: 0.95 },
        required: true,
      },
      {
        id: 'closing',
        type: 'timed_speech',
        title: 'Returning',
        content: 'Coming back',
        speechSegments: [
          { text: 'Begin to bring your awareness back to the room.', pauseAfter: 4 },
          { text: 'Notice any sounds around you.', pauseAfter: 4 },
          { text: 'Wiggle your fingers and toes.', pauseAfter: 3 },
          { text: 'When you are ready, gently open your eyes.', pauseAfter: 4 },
          { text: 'Carry this sense of calm with you.', pauseAfter: 2 },
        ],
        voiceConfig: { rate: 0.8, pitch: 0.95 },
        required: true,
      },
    ],
  },

  {
    id: 'body-scan-10min',
    type: 'meditation',
    category: 'mindfulness_basics',
    name: 'Body Scan',
    description: 'Progressive relaxation through body awareness',
    duration: 10,
    icon: 'body-outline',
    color: '#7C3AED',
    steps: [
      {
        id: 'intro',
        type: 'timed_speech',
        title: 'Settling In',
        content: 'Prepare for the body scan',
        speechSegments: [
          { text: 'Lie down or sit comfortably.', pauseAfter: 3 },
          { text: 'Close your eyes and take three deep breaths.', pauseAfter: 8, breathCue: true },
          { text: 'Allow your body to feel heavy and supported.', pauseAfter: 5 },
        ],
        voiceConfig: { rate: 0.75, pitch: 0.95 },
        required: true,
      },
      {
        id: 'scan',
        type: 'timed_speech',
        title: 'Body Scan',
        content: 'Moving through the body',
        speechSegments: [
          { text: 'Bring your attention to the top of your head.', pauseAfter: 6 },
          { text: 'Notice any sensations there. Tingling, warmth, or nothing at all.', pauseAfter: 8 },
          { text: 'Now move your awareness to your forehead.', pauseAfter: 5 },
          { text: 'Let any tension soften and release.', pauseAfter: 8 },
          { text: 'Bring attention to your eyes and cheeks.', pauseAfter: 6 },
          { text: 'Relax the muscles around your eyes.', pauseAfter: 8 },
          { text: 'Notice your jaw. Let it unclench and soften.', pauseAfter: 8 },
          { text: 'Move awareness down to your neck and shoulders.', pauseAfter: 6 },
          { text: 'These areas often hold tension. Let them relax.', pauseAfter: 10 },
          { text: 'Feel your arms, from shoulders to fingertips.', pauseAfter: 8 },
          { text: 'Notice any sensations. Allow them to be.', pauseAfter: 10 },
          { text: 'Bring attention to your chest.', pauseAfter: 5 },
          { text: 'Feel it rise and fall with each breath.', pauseAfter: 10 },
          { text: 'Move awareness to your belly.', pauseAfter: 5 },
          { text: 'Let it be soft and relaxed.', pauseAfter: 10 },
          { text: 'Notice your lower back and hips.', pauseAfter: 6 },
          { text: 'Release any holding or gripping.', pauseAfter: 10 },
          { text: 'Feel your legs, from thighs to toes.', pauseAfter: 8 },
          { text: 'Let them feel heavy and grounded.', pauseAfter: 10 },
          { text: 'Now feel your whole body as one.', pauseAfter: 6 },
          { text: 'Breathing. Present. At ease.', pauseAfter: 15 },
        ],
        voiceConfig: { rate: 0.7, pitch: 0.95 },
        required: true,
      },
      {
        id: 'closing',
        type: 'timed_speech',
        title: 'Awakening',
        content: 'Returning to awareness',
        speechSegments: [
          { text: 'Slowly begin to deepen your breath.', pauseAfter: 5 },
          { text: 'Gently move your fingers and toes.', pauseAfter: 4 },
          { text: 'Stretch if it feels good.', pauseAfter: 4 },
          { text: 'When ready, open your eyes.', pauseAfter: 3 },
        ],
        voiceConfig: { rate: 0.8, pitch: 0.95 },
        required: true,
      },
    ],
  },

  {
    id: 'silent-meditation',
    type: 'meditation',
    category: 'mindfulness_basics',
    name: 'Silent Timer',
    description: 'Self-guided practice with gentle interval bells',
    duration: 10,
    icon: 'timer-outline',
    color: '#6366F1',
    steps: [
      {
        id: 'timer',
        type: 'meditation_timer',
        title: 'Silent Meditation',
        content: 'Meditate in your own way',
        duration: 600,
        intervalBellSeconds: 120,
        showBreathingGuide: true,
        required: true,
      },
    ],
  },

  // SLEEP & RELAXATION
  {
    id: 'sleep-relaxation',
    type: 'meditation',
    category: 'sleep_relaxation',
    name: 'Sleep Relaxation',
    description: 'Gentle guidance to help you drift off to sleep',
    duration: 12,
    icon: 'moon-outline',
    color: '#6366F1',
    steps: [
      {
        id: 'intro',
        type: 'timed_speech',
        title: 'Preparing for Sleep',
        content: 'Letting go of the day',
        speechSegments: [
          { text: 'Settle into your bed.', pauseAfter: 4 },
          { text: 'Close your eyes.', pauseAfter: 3 },
          { text: 'Take a slow, deep breath in.', pauseAfter: 5, breathCue: true },
          { text: 'And let it all go.', pauseAfter: 5, breathCue: true },
          { text: 'Let the day fade away.', pauseAfter: 5 },
          { text: 'This moment is for rest.', pauseAfter: 5 },
        ],
        voiceConfig: { rate: 0.65, pitch: 0.9 },
        required: true,
      },
      {
        id: 'relaxation',
        type: 'timed_speech',
        title: 'Deep Relaxation',
        content: 'Releasing tension',
        speechSegments: [
          { text: 'Feel your body sinking into the mattress.', pauseAfter: 8 },
          { text: 'Let your head feel heavy on the pillow.', pauseAfter: 8 },
          { text: 'Release your shoulders.', pauseAfter: 6 },
          { text: 'Let them drop away from your ears.', pauseAfter: 8 },
          { text: 'Your arms are heavy. Your hands are soft.', pauseAfter: 10 },
          { text: 'Feel your back melting into the bed.', pauseAfter: 10 },
          { text: 'Your legs are relaxed. Your feet are still.', pauseAfter: 10 },
          { text: 'Your whole body is supported.', pauseAfter: 8 },
          { text: 'Nothing to do. Nowhere to go.', pauseAfter: 10 },
          { text: 'Just rest.', pauseAfter: 15 },
        ],
        voiceConfig: { rate: 0.6, pitch: 0.9 },
        required: true,
      },
      {
        id: 'drift',
        type: 'timed_speech',
        title: 'Drifting Off',
        content: 'Into sleep',
        speechSegments: [
          { text: 'Imagine a warm wave of relaxation.', pauseAfter: 8 },
          { text: 'It starts at the top of your head.', pauseAfter: 8 },
          { text: 'Slowly flowing down through your body.', pauseAfter: 10 },
          { text: 'Washing away any remaining tension.', pauseAfter: 10 },
          { text: 'You are safe. You are calm.', pauseAfter: 10 },
          { text: 'Let yourself drift.', pauseAfter: 15 },
          { text: 'Into peaceful sleep.', pauseAfter: 20 },
        ],
        voiceConfig: { rate: 0.55, pitch: 0.85 },
        required: true,
      },
    ],
  },

  // ANXIETY & STRESS
  {
    id: 'calming-anxiety',
    type: 'meditation',
    category: 'anxiety_stress',
    name: 'Calming Anxiety',
    description: 'Find relief from anxious feelings',
    duration: 7,
    icon: 'water-outline',
    color: '#0EA5E9',
    steps: [
      {
        id: 'grounding',
        type: 'timed_speech',
        title: 'Grounding',
        content: 'Coming back to the present',
        speechSegments: [
          { text: 'Wherever you are, pause for a moment.', pauseAfter: 4 },
          { text: 'Place your feet firmly on the ground.', pauseAfter: 4 },
          { text: 'Feel the solid earth beneath you.', pauseAfter: 5 },
          { text: 'You are here. You are safe.', pauseAfter: 5 },
          { text: 'Take a deep breath in through your nose.', pauseAfter: 5, breathCue: true },
          { text: 'And slowly release it through your mouth.', pauseAfter: 5, breathCue: true },
          { text: 'Let go of what you cannot control.', pauseAfter: 6 },
        ],
        voiceConfig: { rate: 0.8, pitch: 0.95 },
        required: true,
      },
      {
        id: 'calming',
        type: 'timed_speech',
        title: 'Finding Calm',
        content: 'Soothing the nervous system',
        speechSegments: [
          { text: 'Anxiety is just energy in your body.', pauseAfter: 5 },
          { text: 'It cannot hurt you. It will pass.', pauseAfter: 6 },
          { text: 'Notice where you feel it most.', pauseAfter: 6 },
          { text: 'Breathe into that space.', pauseAfter: 6, breathCue: true },
          { text: 'Imagine each exhale releasing tension.', pauseAfter: 8 },
          { text: 'Your body knows how to calm itself.', pauseAfter: 6 },
          { text: 'Trust this process.', pauseAfter: 8 },
          { text: 'With each breath, you feel more at ease.', pauseAfter: 8 },
          { text: 'More grounded. More present.', pauseAfter: 8 },
          { text: 'You are doing well.', pauseAfter: 10 },
        ],
        voiceConfig: { rate: 0.75, pitch: 0.95 },
        required: true,
      },
      {
        id: 'affirmation',
        type: 'timed_speech',
        title: 'Affirmation',
        content: 'Positive reminders',
        speechSegments: [
          { text: 'Repeat silently if it helps.', pauseAfter: 3 },
          { text: 'I am safe in this moment.', pauseAfter: 5 },
          { text: 'I can handle whatever comes.', pauseAfter: 5 },
          { text: 'This feeling is temporary.', pauseAfter: 5 },
          { text: 'I am stronger than my anxiety.', pauseAfter: 5 },
          { text: 'Take one more deep breath.', pauseAfter: 5, breathCue: true },
          { text: 'You are ready to continue your day.', pauseAfter: 3 },
        ],
        voiceConfig: { rate: 0.8, pitch: 0.95 },
        required: true,
      },
    ],
  },

  {
    id: 'grounding-meditation',
    type: 'meditation',
    category: 'anxiety_stress',
    name: 'Grounding Practice',
    description: 'Reconnect with the present moment',
    duration: 5,
    icon: 'earth-outline',
    color: '#84CC16',
    steps: [
      {
        id: 'senses',
        type: 'timed_speech',
        title: '5-4-3-2-1 Grounding',
        content: 'Using your senses',
        speechSegments: [
          { text: 'Let us ground ourselves using our senses.', pauseAfter: 4 },
          { text: 'First, notice five things you can see.', pauseAfter: 10 },
          { text: 'Look around slowly. Name them in your mind.', pauseAfter: 12 },
          { text: 'Now, four things you can touch or feel.', pauseAfter: 8 },
          { text: 'The texture of your clothes. The air on your skin.', pauseAfter: 10 },
          { text: 'Three things you can hear.', pauseAfter: 8 },
          { text: 'Listen carefully. Near and far sounds.', pauseAfter: 10 },
          { text: 'Two things you can smell.', pauseAfter: 8 },
          { text: 'Or imagine two comforting scents.', pauseAfter: 8 },
          { text: 'And one thing you can taste.', pauseAfter: 6 },
          { text: 'Or one positive thing about yourself.', pauseAfter: 8 },
        ],
        voiceConfig: { rate: 0.8, pitch: 0.95 },
        required: true,
      },
      {
        id: 'close',
        type: 'timed_speech',
        title: 'Centered',
        content: 'Feeling grounded',
        speechSegments: [
          { text: 'Take a breath.', pauseAfter: 4, breathCue: true },
          { text: 'You are here. You are present.', pauseAfter: 4 },
          { text: 'You are grounded in this moment.', pauseAfter: 4 },
        ],
        voiceConfig: { rate: 0.8, pitch: 0.95 },
        required: true,
      },
    ],
  },
];
