import type { ExerciseTemplate } from '@/src/types/exercise';

// Voice configuration presets for sleep stories
const VOICE_CONFIG = {
  intro: { rate: 0.6, pitch: 0.9 },
  story: { rate: 0.55, pitch: 0.88 },
  drift: { rate: 0.5, pitch: 0.85 },
};

export const SLEEP_STORY_TEMPLATES: ExerciseTemplate[] = [
  // ============================================
  // SLEEP_NATURE - Forest Path (FREE)
  // ============================================
  {
    id: 'sleep-forest-path',
    type: 'meditation',
    category: 'sleep_nature',
    name: 'Forest Path',
    description: 'Drift off on a peaceful walk through an ancient forest',
    duration: 15,
    icon: 'leaf-outline',
    color: '#059669',
    isPremium: false,
    steps: [
      {
        id: 'intro',
        type: 'timed_speech',
        title: 'Settling In',
        content: 'Find your comfortable position',
        speechSegments: [
          { text: 'Settle into your bed, finding the most comfortable position.', pauseAfter: 5 },
          { text: 'Close your eyes gently.', pauseAfter: 4 },
          { text: 'Take a slow, deep breath in.', pauseAfter: 5, breathCue: true },
          { text: 'And let it flow out naturally.', pauseAfter: 6, breathCue: true },
          { text: 'Tonight, we are going on a journey through an ancient forest.', pauseAfter: 5 },
          { text: 'There is nothing you need to do but listen and drift.', pauseAfter: 8 },
        ],
        voiceConfig: VOICE_CONFIG.intro,
        required: true,
      },
      {
        id: 'story-1',
        type: 'timed_speech',
        title: 'The Forest Awakens',
        content: 'Entering the woods',
        speechSegments: [
          { text: 'Imagine yourself standing at the edge of a vast, ancient forest.', pauseAfter: 8 },
          { text: 'The trees tower above you, their leaves creating a soft green canopy.', pauseAfter: 10 },
          { text: 'Sunlight filters through in gentle, golden rays.', pauseAfter: 8 },
          { text: 'The air is cool and fresh. Each breath fills you with calm.', pauseAfter: 10 },
          { text: 'You step onto the soft path, covered in moss and fallen leaves.', pauseAfter: 8 },
          { text: 'With each step, you feel the day melting away.', pauseAfter: 12 },
          { text: 'The forest welcomes you.', pauseAfter: 15 },
        ],
        voiceConfig: VOICE_CONFIG.story,
        required: true,
      },
      {
        id: 'story-2',
        type: 'timed_speech',
        title: 'Deeper Into the Woods',
        content: 'Walking the path',
        speechSegments: [
          { text: 'You continue walking, the path winding gently through the trees.', pauseAfter: 10 },
          { text: 'In the distance, you hear the soft trickle of a stream.', pauseAfter: 10 },
          { text: 'Birds sing their evening songs, soft and far away.', pauseAfter: 12 },
          { text: 'The forest floor is springy beneath your feet.', pauseAfter: 8 },
          { text: 'You notice a fallen log covered in soft, emerald moss.', pauseAfter: 8 },
          { text: 'It looks like the perfect place to rest.', pauseAfter: 10 },
          { text: 'You sit down, feeling completely at peace.', pauseAfter: 15 },
        ],
        voiceConfig: VOICE_CONFIG.story,
        required: true,
      },
      {
        id: 'story-3',
        type: 'timed_speech',
        title: 'The Quiet Clearing',
        content: 'Finding peace',
        speechSegments: [
          { text: 'Ahead, you see a small clearing bathed in soft twilight.', pauseAfter: 10 },
          { text: 'You walk towards it, your footsteps silent on the mossy ground.', pauseAfter: 10 },
          { text: 'In the center of the clearing is a bed of soft ferns.', pauseAfter: 8 },
          { text: 'You lie down, the ferns cushioning you like a cloud.', pauseAfter: 10 },
          { text: 'Above you, the first stars begin to appear through the canopy.', pauseAfter: 12 },
          { text: 'The forest wraps around you, protective and warm.', pauseAfter: 15 },
        ],
        voiceConfig: VOICE_CONFIG.story,
        required: true,
      },
      {
        id: 'drift',
        type: 'timed_speech',
        title: 'Drifting Away',
        content: 'Into peaceful sleep',
        speechSegments: [
          { text: 'The forest grows quieter now.', pauseAfter: 12 },
          { text: 'A warm, gentle breeze wraps around you like a blanket.', pauseAfter: 10 },
          { text: 'Your eyes grow heavy.', pauseAfter: 8 },
          { text: 'The sounds of the forest fade into a soft, distant hum.', pauseAfter: 12 },
          { text: 'You are safe here. Protected by the ancient trees.', pauseAfter: 15 },
          { text: 'Let yourself drift now.', pauseAfter: 12 },
          { text: 'Deeper and deeper into peaceful sleep.', pauseAfter: 20 },
          { text: 'Sleep well.', pauseAfter: 30 },
        ],
        voiceConfig: VOICE_CONFIG.drift,
        required: true,
      },
    ],
  },

  // ============================================
  // SLEEP_FANTASY - Cloud Float (FREE)
  // ============================================
  {
    id: 'sleep-cloud-float',
    type: 'meditation',
    category: 'sleep_fantasy',
    name: 'Cloud Float',
    description: 'Float away on a soft, dreamy cloud',
    duration: 12,
    icon: 'cloud-outline',
    color: '#8b5cf6',
    isPremium: false,
    steps: [
      {
        id: 'intro',
        type: 'timed_speech',
        title: 'Preparing to Float',
        content: 'Let go of the day',
        speechSegments: [
          { text: 'Make yourself comfortable and close your eyes.', pauseAfter: 5 },
          { text: 'Take a deep breath in, filling your lungs completely.', pauseAfter: 5, breathCue: true },
          { text: 'And slowly release it, letting go of any tension.', pauseAfter: 6, breathCue: true },
          { text: 'Tonight, you will float on a cloud, drifting through a peaceful sky.', pauseAfter: 6 },
          { text: 'Let your body become light.', pauseAfter: 8 },
        ],
        voiceConfig: VOICE_CONFIG.intro,
        required: true,
      },
      {
        id: 'story-1',
        type: 'timed_speech',
        title: 'The Cloud Arrives',
        content: 'Your soft cloud',
        speechSegments: [
          { text: 'Imagine a soft, fluffy cloud descending from the sky.', pauseAfter: 8 },
          { text: 'It gently floats down to where you lie.', pauseAfter: 8 },
          { text: 'The cloud is softer than the softest pillow.', pauseAfter: 8 },
          { text: 'You step onto it, and it holds you perfectly.', pauseAfter: 10 },
          { text: 'The cloud begins to rise, slowly and gently.', pauseAfter: 10 },
          { text: 'You feel completely safe as you float upward.', pauseAfter: 12 },
        ],
        voiceConfig: VOICE_CONFIG.story,
        required: true,
      },
      {
        id: 'story-2',
        type: 'timed_speech',
        title: 'Floating in the Sky',
        content: 'Among the stars',
        speechSegments: [
          { text: 'You are now floating high above, among gentle wisps of cloud.', pauseAfter: 10 },
          { text: 'The evening sky stretches endlessly around you.', pauseAfter: 8 },
          { text: 'Soft shades of purple and pink paint the horizon.', pauseAfter: 10 },
          { text: 'Stars begin to appear, twinkling softly.', pauseAfter: 10 },
          { text: 'Each star sends down a gentle, warm light.', pauseAfter: 10 },
          { text: 'You feel weightless, peaceful, and completely relaxed.', pauseAfter: 12 },
        ],
        voiceConfig: VOICE_CONFIG.story,
        required: true,
      },
      {
        id: 'drift',
        type: 'timed_speech',
        title: 'Drifting to Sleep',
        content: 'Peaceful rest',
        speechSegments: [
          { text: 'Your cloud drifts slowly, carrying you through the peaceful night.', pauseAfter: 12 },
          { text: 'The gentle motion soothes you even more.', pauseAfter: 10 },
          { text: 'Your body feels so light, so relaxed.', pauseAfter: 10 },
          { text: 'The stars above seem to sing a silent lullaby.', pauseAfter: 12 },
          { text: 'You can let go now.', pauseAfter: 10 },
          { text: 'Float into dreams.', pauseAfter: 15 },
          { text: 'Sleep peacefully.', pauseAfter: 30 },
        ],
        voiceConfig: VOICE_CONFIG.drift,
        required: true,
      },
    ],
  },

  // ============================================
  // SLEEP_COZY - Rainy Window (FREE)
  // ============================================
  {
    id: 'sleep-rainy-window',
    type: 'meditation',
    category: 'sleep_cozy',
    name: 'Rainy Window',
    description: 'Listen to rain as you drift to sleep in a cozy room',
    duration: 10,
    icon: 'water-outline',
    color: '#6366f1',
    isPremium: false,
    steps: [
      {
        id: 'intro',
        type: 'timed_speech',
        title: 'Getting Cozy',
        content: 'Settle in',
        speechSegments: [
          { text: 'Wrap yourself in your blankets and get comfortable.', pauseAfter: 5 },
          { text: 'Close your eyes and take a deep, relaxing breath.', pauseAfter: 5, breathCue: true },
          { text: 'Let your body sink into the bed.', pauseAfter: 6 },
          { text: 'Tonight, imagine you are in a cozy room on a rainy evening.', pauseAfter: 6 },
        ],
        voiceConfig: VOICE_CONFIG.intro,
        required: true,
      },
      {
        id: 'story-1',
        type: 'timed_speech',
        title: 'The Cozy Room',
        content: 'Your safe space',
        speechSegments: [
          { text: 'You are lying in a soft bed by a large window.', pauseAfter: 8 },
          { text: 'Outside, gentle rain begins to fall.', pauseAfter: 8 },
          { text: 'You can hear the soft patter of raindrops on the glass.', pauseAfter: 10 },
          { text: 'The room is warm and dimly lit by a soft lamp.', pauseAfter: 8 },
          { text: 'A thick, cozy blanket surrounds you completely.', pauseAfter: 10 },
          { text: 'This is your safe, peaceful space.', pauseAfter: 12 },
        ],
        voiceConfig: VOICE_CONFIG.story,
        required: true,
      },
      {
        id: 'story-2',
        type: 'timed_speech',
        title: 'The Rain Falls',
        content: 'Nature\'s lullaby',
        speechSegments: [
          { text: 'The rain continues to fall, steady and gentle.', pauseAfter: 10 },
          { text: 'Each drop creates a soft rhythm on the window.', pauseAfter: 10 },
          { text: 'You feel the coolness of the air from outside.', pauseAfter: 8 },
          { text: 'But inside, you are perfectly warm and safe.', pauseAfter: 10 },
          { text: 'The rain washes away all the thoughts of the day.', pauseAfter: 12 },
          { text: 'Only peace remains.', pauseAfter: 15 },
        ],
        voiceConfig: VOICE_CONFIG.story,
        required: true,
      },
      {
        id: 'drift',
        type: 'timed_speech',
        title: 'Falling Asleep',
        content: 'Rest now',
        speechSegments: [
          { text: 'The rain continues its gentle song.', pauseAfter: 10 },
          { text: 'Your eyes are heavy now.', pauseAfter: 8 },
          { text: 'The warmth of the blanket feels so good.', pauseAfter: 10 },
          { text: 'Let the rain carry you to sleep.', pauseAfter: 12 },
          { text: 'You are safe. You are warm.', pauseAfter: 12 },
          { text: 'Sleep now.', pauseAfter: 30 },
        ],
        voiceConfig: VOICE_CONFIG.drift,
        required: true,
      },
    ],
  },

  // ============================================
  // SLEEP_GUIDED - Body Release (FREE)
  // ============================================
  {
    id: 'sleep-body-release',
    type: 'meditation',
    category: 'sleep_guided',
    name: 'Body Release',
    description: 'Progressive relaxation to release tension and drift off',
    duration: 12,
    icon: 'body-outline',
    color: '#14b8a6',
    isPremium: false,
    steps: [
      {
        id: 'intro',
        type: 'timed_speech',
        title: 'Preparing to Relax',
        content: 'Begin your relaxation',
        speechSegments: [
          { text: 'Lie comfortably and let your body settle.', pauseAfter: 5 },
          { text: 'Close your eyes gently.', pauseAfter: 4 },
          { text: 'Take a slow, deep breath.', pauseAfter: 5, breathCue: true },
          { text: 'And release it completely.', pauseAfter: 6, breathCue: true },
          { text: 'We will now release all tension from your body, one area at a time.', pauseAfter: 6 },
          { text: 'There is nothing to do but relax.', pauseAfter: 8 },
        ],
        voiceConfig: VOICE_CONFIG.intro,
        required: true,
      },
      {
        id: 'body-1',
        type: 'timed_speech',
        title: 'Head and Face',
        content: 'Releasing tension',
        speechSegments: [
          { text: 'Begin by noticing your forehead.', pauseAfter: 6 },
          { text: 'Allow any tension there to melt away.', pauseAfter: 8 },
          { text: 'Feel your eyebrows soften.', pauseAfter: 6 },
          { text: 'Let your eyes rest gently in their sockets.', pauseAfter: 8 },
          { text: 'Relax your jaw, letting your mouth fall slightly open.', pauseAfter: 8 },
          { text: 'Your entire face is soft and peaceful now.', pauseAfter: 10 },
        ],
        voiceConfig: VOICE_CONFIG.story,
        required: true,
      },
      {
        id: 'body-2',
        type: 'timed_speech',
        title: 'Neck and Shoulders',
        content: 'Letting go',
        speechSegments: [
          { text: 'Move your attention to your neck.', pauseAfter: 6 },
          { text: 'Feel any tightness dissolve.', pauseAfter: 8 },
          { text: 'Your neck is soft and relaxed.', pauseAfter: 8 },
          { text: 'Now notice your shoulders.', pauseAfter: 6 },
          { text: 'Let them drop down, away from your ears.', pauseAfter: 8 },
          { text: 'Feel the weight release from your shoulders completely.', pauseAfter: 10 },
          { text: 'Heavy and relaxed.', pauseAfter: 10 },
        ],
        voiceConfig: VOICE_CONFIG.story,
        required: true,
      },
      {
        id: 'body-3',
        type: 'timed_speech',
        title: 'Arms and Hands',
        content: 'Complete relaxation',
        speechSegments: [
          { text: 'The relaxation flows down into your arms.', pauseAfter: 8 },
          { text: 'Your upper arms become heavy and warm.', pauseAfter: 8 },
          { text: 'Your forearms relax completely.', pauseAfter: 8 },
          { text: 'Feel your hands soften.', pauseAfter: 6 },
          { text: 'Your fingers uncurl naturally.', pauseAfter: 8 },
          { text: 'Your arms are completely at rest.', pauseAfter: 10 },
        ],
        voiceConfig: VOICE_CONFIG.story,
        required: true,
      },
      {
        id: 'body-4',
        type: 'timed_speech',
        title: 'Core and Legs',
        content: 'Deep release',
        speechSegments: [
          { text: 'Feel your chest and stomach relax with each breath.', pauseAfter: 8 },
          { text: 'Your back sinks deeper into the bed.', pauseAfter: 8 },
          { text: 'The relaxation continues down through your hips.', pauseAfter: 8 },
          { text: 'Your thighs become heavy and still.', pauseAfter: 8 },
          { text: 'Your calves relax.', pauseAfter: 6 },
          { text: 'Your feet become soft and warm.', pauseAfter: 8 },
          { text: 'Your entire body is completely relaxed.', pauseAfter: 12 },
        ],
        voiceConfig: VOICE_CONFIG.story,
        required: true,
      },
      {
        id: 'drift',
        type: 'timed_speech',
        title: 'Drifting Off',
        content: 'Into sleep',
        speechSegments: [
          { text: 'Your body is at total peace.', pauseAfter: 10 },
          { text: 'There is nothing to hold onto.', pauseAfter: 8 },
          { text: 'Nothing to think about.', pauseAfter: 8 },
          { text: 'Just this deep, beautiful relaxation.', pauseAfter: 10 },
          { text: 'Let yourself drift now.', pauseAfter: 12 },
          { text: 'Into peaceful sleep.', pauseAfter: 15 },
          { text: 'Rest well.', pauseAfter: 30 },
        ],
        voiceConfig: VOICE_CONFIG.drift,
        required: true,
      },
    ],
  },

  // ============================================
  // SLEEP_NATURE - Ocean Shore (PREMIUM)
  // ============================================
  {
    id: 'sleep-ocean-shore',
    type: 'meditation',
    category: 'sleep_nature',
    name: 'Ocean Shore',
    description: 'Fall asleep to the rhythm of gentle waves on a quiet beach',
    duration: 18,
    icon: 'water-outline',
    color: '#0ea5e9',
    isPremium: true,
    steps: [
      {
        id: 'intro',
        type: 'timed_speech',
        title: 'Arriving at the Shore',
        content: 'Begin your journey',
        speechSegments: [
          { text: 'Close your eyes and let your body relax.', pauseAfter: 5 },
          { text: 'Take a slow, deep breath in.', pauseAfter: 5, breathCue: true },
          { text: 'And gently exhale.', pauseAfter: 6, breathCue: true },
          { text: 'Tonight, you are resting on a peaceful beach at twilight.', pauseAfter: 6 },
          { text: 'The ocean stretches endlessly before you.', pauseAfter: 8 },
        ],
        voiceConfig: VOICE_CONFIG.intro,
        required: true,
      },
      {
        id: 'story-1',
        type: 'timed_speech',
        title: 'The Sandy Beach',
        content: 'Your resting place',
        speechSegments: [
          { text: 'You lie on soft, warm sand.', pauseAfter: 8 },
          { text: 'The sand has been warmed by the sun all day.', pauseAfter: 8 },
          { text: 'It cradles your body perfectly.', pauseAfter: 8 },
          { text: 'Above you, the sky is painted in soft oranges and purples.', pauseAfter: 10 },
          { text: 'A gentle breeze carries the fresh scent of the sea.', pauseAfter: 10 },
          { text: 'You feel completely at peace.', pauseAfter: 12 },
        ],
        voiceConfig: VOICE_CONFIG.story,
        required: true,
      },
      {
        id: 'story-2',
        type: 'timed_speech',
        title: 'The Rhythm of Waves',
        content: 'Nature\'s lullaby',
        speechSegments: [
          { text: 'Listen to the waves as they wash gently onto the shore.', pauseAfter: 10 },
          { text: 'In and out. In and out.', pauseAfter: 12 },
          { text: 'Each wave brings relaxation.', pauseAfter: 8 },
          { text: 'Each wave carries away any remaining tension.', pauseAfter: 10 },
          { text: 'The rhythm is ancient and eternal.', pauseAfter: 10 },
          { text: 'It has soothed countless souls before you.', pauseAfter: 12 },
          { text: 'Now it soothes you.', pauseAfter: 15 },
        ],
        voiceConfig: VOICE_CONFIG.story,
        required: true,
      },
      {
        id: 'story-3',
        type: 'timed_speech',
        title: 'Twilight Descends',
        content: 'The peaceful evening',
        speechSegments: [
          { text: 'The sun has set now, leaving behind a soft glow on the horizon.', pauseAfter: 10 },
          { text: 'Stars begin to appear, one by one.', pauseAfter: 10 },
          { text: 'The waves continue their gentle rhythm.', pauseAfter: 10 },
          { text: 'The air is warm and salty.', pauseAfter: 8 },
          { text: 'You feel the sand beneath you, supporting you completely.', pauseAfter: 10 },
          { text: 'There is nowhere else to be. Nothing else to do.', pauseAfter: 12 },
        ],
        voiceConfig: VOICE_CONFIG.story,
        required: true,
      },
      {
        id: 'drift',
        type: 'timed_speech',
        title: 'Drifting with the Tide',
        content: 'Into peaceful sleep',
        speechSegments: [
          { text: 'The waves grow softer now, a distant whisper.', pauseAfter: 12 },
          { text: 'Your body feels as light as the sea foam.', pauseAfter: 10 },
          { text: 'The night wraps around you like a warm blanket.', pauseAfter: 10 },
          { text: 'Let the ocean carry your thoughts away.', pauseAfter: 12 },
          { text: 'Drift with the gentle tide.', pauseAfter: 12 },
          { text: 'Into deep, peaceful sleep.', pauseAfter: 15 },
          { text: 'Sleep well.', pauseAfter: 30 },
        ],
        voiceConfig: VOICE_CONFIG.drift,
        required: true,
      },
    ],
  },

  // ============================================
  // SLEEP_FANTASY - Starlit Voyage (PREMIUM)
  // ============================================
  {
    id: 'sleep-starlit-voyage',
    type: 'meditation',
    category: 'sleep_fantasy',
    name: 'Starlit Voyage',
    description: 'Journey through the cosmos on a magical starlit adventure',
    duration: 15,
    icon: 'star-outline',
    color: '#a855f7',
    isPremium: true,
    steps: [
      {
        id: 'intro',
        type: 'timed_speech',
        title: 'Preparing for Launch',
        content: 'Begin your cosmic journey',
        speechSegments: [
          { text: 'Settle into a comfortable position and close your eyes.', pauseAfter: 5 },
          { text: 'Breathe deeply, letting go of the earth below.', pauseAfter: 6, breathCue: true },
          { text: 'Tonight, you will travel among the stars.', pauseAfter: 6 },
          { text: 'Feel your body becoming lighter.', pauseAfter: 6 },
          { text: 'Lighter and lighter still.', pauseAfter: 8 },
        ],
        voiceConfig: VOICE_CONFIG.intro,
        required: true,
      },
      {
        id: 'story-1',
        type: 'timed_speech',
        title: 'Rising into the Night',
        content: 'Leaving earth behind',
        speechSegments: [
          { text: 'You begin to float gently upward.', pauseAfter: 8 },
          { text: 'The world below grows smaller and more peaceful.', pauseAfter: 10 },
          { text: 'Cities become tiny lights, then fade away.', pauseAfter: 10 },
          { text: 'You pass through soft clouds that caress you gently.', pauseAfter: 10 },
          { text: 'Above you, the infinite universe awaits.', pauseAfter: 12 },
          { text: 'You feel no fear. Only wonder.', pauseAfter: 12 },
        ],
        voiceConfig: VOICE_CONFIG.story,
        required: true,
      },
      {
        id: 'story-2',
        type: 'timed_speech',
        title: 'Among the Stars',
        content: 'The cosmic dance',
        speechSegments: [
          { text: 'You are now surrounded by stars.', pauseAfter: 8 },
          { text: 'Millions of them, each one a gentle light.', pauseAfter: 10 },
          { text: 'They twinkle and dance around you.', pauseAfter: 10 },
          { text: 'Some are warm gold, others cool blue.', pauseAfter: 8 },
          { text: 'A distant nebula glows with purple and pink light.', pauseAfter: 10 },
          { text: 'You drift slowly through this sea of stars.', pauseAfter: 12 },
          { text: 'Peaceful. Weightless. Free.', pauseAfter: 15 },
        ],
        voiceConfig: VOICE_CONFIG.story,
        required: true,
      },
      {
        id: 'story-3',
        type: 'timed_speech',
        title: 'The Cosmic Cradle',
        content: 'Your resting place',
        speechSegments: [
          { text: 'You come to rest in a gentle cloud of stardust.', pauseAfter: 10 },
          { text: 'It glimmers softly, cradling you like a hammock.', pauseAfter: 10 },
          { text: 'The stars around you seem to pulse with a soothing rhythm.', pauseAfter: 10 },
          { text: 'Each pulse sends waves of relaxation through you.', pauseAfter: 10 },
          { text: 'You are part of the universe now.', pauseAfter: 10 },
          { text: 'Connected to everything. At peace with all.', pauseAfter: 12 },
        ],
        voiceConfig: VOICE_CONFIG.story,
        required: true,
      },
      {
        id: 'drift',
        type: 'timed_speech',
        title: 'Dreaming Among Stars',
        content: 'Into cosmic sleep',
        speechSegments: [
          { text: 'The stardust cradle rocks you gently.', pauseAfter: 12 },
          { text: 'Back and forth. Back and forth.', pauseAfter: 10 },
          { text: 'The stars sing a silent lullaby.', pauseAfter: 12 },
          { text: 'Your eyes are so heavy now.', pauseAfter: 10 },
          { text: 'Let the cosmos hold you.', pauseAfter: 12 },
          { text: 'Dream among the stars.', pauseAfter: 15 },
          { text: 'Sleep peacefully.', pauseAfter: 30 },
        ],
        voiceConfig: VOICE_CONFIG.drift,
        required: true,
      },
    ],
  },

  // ============================================
  // SLEEP_COZY - Cabin Fireplace (PREMIUM)
  // ============================================
  {
    id: 'sleep-cabin-fireplace',
    type: 'meditation',
    category: 'sleep_cozy',
    name: 'Cabin Fireplace',
    description: 'Relax by a warm fire in a cozy mountain cabin',
    duration: 15,
    icon: 'flame-outline',
    color: '#f97316',
    isPremium: true,
    steps: [
      {
        id: 'intro',
        type: 'timed_speech',
        title: 'Arriving at the Cabin',
        content: 'Your mountain retreat',
        speechSegments: [
          { text: 'Close your eyes and take a deep breath.', pauseAfter: 5 },
          { text: 'Let your body relax completely.', pauseAfter: 5 },
          { text: 'Tonight, you are in a cozy cabin in the mountains.', pauseAfter: 6 },
          { text: 'Outside, snow falls gently. Inside, a fire crackles warmly.', pauseAfter: 8 },
          { text: 'You are safe and warm.', pauseAfter: 8 },
        ],
        voiceConfig: VOICE_CONFIG.intro,
        required: true,
      },
      {
        id: 'story-1',
        type: 'timed_speech',
        title: 'The Warm Cabin',
        content: 'Your cozy retreat',
        speechSegments: [
          { text: 'You sink into a large, comfortable armchair by the fireplace.', pauseAfter: 8 },
          { text: 'The chair is soft and perfectly molds to your body.', pauseAfter: 8 },
          { text: 'A thick wool blanket covers you from shoulders to toes.', pauseAfter: 10 },
          { text: 'The fire dances before you, casting gentle, warm light.', pauseAfter: 10 },
          { text: 'You can feel the heat on your face. So soothing.', pauseAfter: 10 },
          { text: 'The smell of burning wood fills the air.', pauseAfter: 12 },
        ],
        voiceConfig: VOICE_CONFIG.story,
        required: true,
      },
      {
        id: 'story-2',
        type: 'timed_speech',
        title: 'The Crackling Fire',
        content: 'Hypnotic flames',
        speechSegments: [
          { text: 'Watch the flames as they dance and flicker.', pauseAfter: 10 },
          { text: 'Orange. Yellow. Sometimes a flash of blue.', pauseAfter: 10 },
          { text: 'The wood crackles and pops softly.', pauseAfter: 10 },
          { text: 'Each sound deepens your relaxation.', pauseAfter: 8 },
          { text: 'The warmth wraps around you like an embrace.', pauseAfter: 10 },
          { text: 'Outside, the world is cold and quiet.', pauseAfter: 8 },
          { text: 'But here, you are perfectly warm.', pauseAfter: 12 },
        ],
        voiceConfig: VOICE_CONFIG.story,
        required: true,
      },
      {
        id: 'story-3',
        type: 'timed_speech',
        title: 'Snow Falls Gently',
        content: 'Peace outside',
        speechSegments: [
          { text: 'Through the window, you see snowflakes drifting down.', pauseAfter: 10 },
          { text: 'They fall slowly, silently, covering everything in white.', pauseAfter: 10 },
          { text: 'The world outside is still and peaceful.', pauseAfter: 10 },
          { text: 'Inside, the fire continues its gentle dance.', pauseAfter: 10 },
          { text: 'You feel your eyes growing heavy.', pauseAfter: 10 },
          { text: 'So warm. So comfortable. So safe.', pauseAfter: 12 },
        ],
        voiceConfig: VOICE_CONFIG.story,
        required: true,
      },
      {
        id: 'drift',
        type: 'timed_speech',
        title: 'Drifting to Sleep',
        content: 'By the warm fire',
        speechSegments: [
          { text: 'The fire crackles softly, like a lullaby.', pauseAfter: 12 },
          { text: 'Your body is completely relaxed.', pauseAfter: 10 },
          { text: 'The warmth holds you close.', pauseAfter: 10 },
          { text: 'Let yourself drift off now.', pauseAfter: 12 },
          { text: 'Into warm, peaceful dreams.', pauseAfter: 15 },
          { text: 'Sleep well.', pauseAfter: 30 },
        ],
        voiceConfig: VOICE_CONFIG.drift,
        required: true,
      },
    ],
  },

  // ============================================
  // SLEEP_TRAVEL - Train Journey (PREMIUM)
  // ============================================
  {
    id: 'sleep-train-journey',
    type: 'meditation',
    category: 'sleep_travel',
    name: 'Night Train',
    description: 'Fall asleep to the gentle rhythm of a train journey',
    duration: 15,
    icon: 'train-outline',
    color: '#64748b',
    isPremium: true,
    steps: [
      {
        id: 'intro',
        type: 'timed_speech',
        title: 'Boarding the Train',
        content: 'Your sleeper car awaits',
        speechSegments: [
          { text: 'Close your eyes and relax.', pauseAfter: 5 },
          { text: 'Take a slow, deep breath.', pauseAfter: 5, breathCue: true },
          { text: 'Tonight, you are aboard a train, traveling through the night.', pauseAfter: 6 },
          { text: 'You have a cozy sleeper compartment all to yourself.', pauseAfter: 6 },
          { text: 'The journey ahead is long and peaceful.', pauseAfter: 8 },
        ],
        voiceConfig: VOICE_CONFIG.intro,
        required: true,
      },
      {
        id: 'story-1',
        type: 'timed_speech',
        title: 'Your Sleeper Compartment',
        content: 'A cozy space',
        speechSegments: [
          { text: 'You lie in a comfortable bed with crisp white sheets.', pauseAfter: 8 },
          { text: 'A small lamp casts a warm, golden glow.', pauseAfter: 8 },
          { text: 'Through the window, the countryside passes slowly by.', pauseAfter: 10 },
          { text: 'The curtains sway gently with the motion of the train.', pauseAfter: 10 },
          { text: 'You feel the gentle rocking. Back and forth.', pauseAfter: 10 },
          { text: 'It is so soothing. So peaceful.', pauseAfter: 12 },
        ],
        voiceConfig: VOICE_CONFIG.story,
        required: true,
      },
      {
        id: 'story-2',
        type: 'timed_speech',
        title: 'The Rhythm of the Rails',
        content: 'A gentle lullaby',
        speechSegments: [
          { text: 'Listen to the rhythm of the wheels on the tracks.', pauseAfter: 10 },
          { text: 'Clickety-clack. Clickety-clack.', pauseAfter: 10 },
          { text: 'A steady, hypnotic rhythm.', pauseAfter: 8 },
          { text: 'The train rocks you gently side to side.', pauseAfter: 10 },
          { text: 'Like a cradle rocking a child.', pauseAfter: 10 },
          { text: 'You feel yourself relaxing more with each gentle sway.', pauseAfter: 12 },
        ],
        voiceConfig: VOICE_CONFIG.story,
        required: true,
      },
      {
        id: 'story-3',
        type: 'timed_speech',
        title: 'The Night Passes',
        content: 'Journey through darkness',
        speechSegments: [
          { text: 'Outside, the night is deep and quiet.', pauseAfter: 10 },
          { text: 'Occasionally, a distant light flickers past.', pauseAfter: 10 },
          { text: 'Small towns sleeping. Fields resting under starlight.', pauseAfter: 10 },
          { text: 'The train carries you onward, safe and warm.', pauseAfter: 10 },
          { text: 'You have nowhere to be. Nothing to do.', pauseAfter: 10 },
          { text: 'Just this peaceful journey through the night.', pauseAfter: 12 },
        ],
        voiceConfig: VOICE_CONFIG.story,
        required: true,
      },
      {
        id: 'drift',
        type: 'timed_speech',
        title: 'Falling Asleep',
        content: 'The train carries you to dreams',
        speechSegments: [
          { text: 'The rhythm of the rails grows softer.', pauseAfter: 12 },
          { text: 'Clickety-clack. Clickety-clack.', pauseAfter: 10 },
          { text: 'Your eyes are so heavy now.', pauseAfter: 10 },
          { text: 'The gentle rocking soothes you completely.', pauseAfter: 12 },
          { text: 'Let the train carry you to your dreams.', pauseAfter: 12 },
          { text: 'Sleep peacefully.', pauseAfter: 15 },
          { text: 'Rest well.', pauseAfter: 30 },
        ],
        voiceConfig: VOICE_CONFIG.drift,
        required: true,
      },
    ],
  },
];
