/**
 * Evidence-based sources for wellness insights
 * Used to provide citations as required by App Store guidelines
 */

export interface WellnessSource {
  id: string;
  title: string;
  organization: string;
  url: string;
  description: string;
}

export const WELLNESS_SOURCES: WellnessSource[] = [
  {
    id: 'apa-mood-tracking',
    title: 'Understanding and Managing Stress',
    organization: 'American Psychological Association',
    url: 'https://www.apa.org/topics/stress',
    description: 'Research on stress management and emotional well-being',
  },
  {
    id: 'nimh-mental-health',
    title: 'Caring for Your Mental Health',
    organization: 'National Institute of Mental Health',
    url: 'https://www.nimh.nih.gov/health/topics/caring-for-your-mental-health',
    description: 'Evidence-based mental health practices',
  },
  {
    id: 'who-mental-health',
    title: 'Mental Health: Strengthening Our Response',
    organization: 'World Health Organization',
    url: 'https://www.who.int/news-room/fact-sheets/detail/mental-health-strengthening-our-response',
    description: 'Global mental health guidelines and best practices',
  },
  {
    id: 'cdc-mental-health',
    title: 'About Mental Health',
    organization: 'Centers for Disease Control and Prevention',
    url: 'https://www.cdc.gov/mental-health/about/',
    description: 'Mental health resources and wellness strategies',
  },
];

export const INSIGHTS_DISCLAIMER = `AI Insights are generated using artificial intelligence to analyze your self-reported mood data. These insights are for informational and self-reflection purposes only. They are not medical advice, diagnosis, or treatment. Always consult a qualified healthcare provider for mental health concerns.`;

export const PATTERN_METHODOLOGY = `Insights are generated by AI analyzing patterns in your mood entries, including correlations between activities, time of day, and reported mood levels. The AI does not have access to external medical databases.`;

export const LEARN_MORE_HEADER = `For evidence-based mental health information, visit:`;
